// GENERATED CODE - DO NOT MODIFY MANUALLY
// **************************************************************************
// Auto generated by https://github.com/fluttercandies/ff_annotation_route
// **************************************************************************
const List<String> routeNames = <String>[
  'fluttercandies://PingLunDemo',
  'fluttercandies://TextFieldPage',
  'fluttercandies://Tik Tok Comment',
  'fluttercandies://loadmore',
  'fluttercandies://mainpage',
  'fluttercandies://nestedscrollview',
  'fluttercandies://pinned header height',
  'fluttercandies://pulltorefresh',
  'fluttercandies://scroll to top',
];

class Routes {
  const Routes._();

  /// 'Tik Tok Comment'
  ///
  /// [name] : 'fluttercandies://PingLunDemo'
  ///
  /// [routeName] : 'pingLundemo'
  ///
  /// [description] : 'Tik Tok Comment'
  ///
  /// [pageRouteType] : PageRouteType.transparent
  static const String fluttercandiesPingLunDemo =
      'fluttercandies://PingLunDemo';

  /// 'Tik Tok Comment'
  ///
  /// [name] : 'fluttercandies://TextFieldPage'
  ///
  /// [routeName] : 'TextFieldPage'
  ///
  /// [description] : 'Tik Tok Comment'
  ///
  /// [arguments] : [text]
  ///
  /// [pageRouteType] : PageRouteType.transparent
  static const String fluttercandiesTextFieldPage =
      'fluttercandies://TextFieldPage';

  /// 'Demo for Tik Tok Comment'
  ///
  /// [name] : 'fluttercandies://Tik Tok Comment'
  ///
  /// [routeName] : 'tiktokcomment'
  ///
  /// [description] : 'Demo for Tik Tok Comment'
  static const String fluttercandiesTikTokComment =
      'fluttercandies://Tik Tok Comment';

  /// "show how to support load more list in NestedScrollView's body without ScrollController"
  ///
  /// [name] : 'fluttercandies://loadmore'
  ///
  /// [routeName] : 'load more demo'
  ///
  /// [description] : "show how to support load more list in NestedScrollView's body without ScrollController"
  static const String fluttercandiesLoadmore = 'fluttercandies://loadmore';

  /// 'MainPage'
  ///
  /// [name] : 'fluttercandies://mainpage'
  ///
  /// [routeName] : 'MainPage'
  static const String fluttercandiesMainpage = 'fluttercandies://mainpage';

  /// 'fix pinned header and inner scrollables sync issues.'
  ///
  /// [name] : 'fluttercandies://nestedscrollview'
  ///
  /// [routeName] : 'NestedScrollview'
  ///
  /// [description] : 'fix pinned header and inner scrollables sync issues.'
  static const String fluttercandiesNestedscrollview =
      'fluttercandies://nestedscrollview';

  /// 'how to change pinned header height dynamically'
  ///
  /// [name] : 'fluttercandies://pinned header height'
  ///
  /// [routeName] : 'pinned header height'
  ///
  /// [description] : 'how to change pinned header height dynamically'
  static const String fluttercandiesPinnedHeaderHeight =
      'fluttercandies://pinned header height';

  /// "how to pull to refresh for list in NestedScrollView's body without ScrollController"
  ///
  /// [name] : 'fluttercandies://pulltorefresh'
  ///
  /// [routeName] : 'pull to refresh'
  ///
  /// [description] : "how to pull to refresh for list in NestedScrollView's body without ScrollController"
  static const String fluttercandiesPulltorefresh =
      'fluttercandies://pulltorefresh';

  /// "how to scroll list to top in NestedScrollView's body without ScrollController"
  ///
  /// [name] : 'fluttercandies://scroll to top'
  ///
  /// [routeName] : 'scroll to top'
  ///
  /// [description] : "how to scroll list to top in NestedScrollView's body without ScrollController"
  static const String fluttercandiesScrollToTop =
      'fluttercandies://scroll to top';
}
