// GENERATED CODE - DO NOT MODIFY BY HAND
// **************************************************************************
// auto generated by https://github.com/fluttercandies/ff_annotation_route
// ************************************************************************** 

import 'package:flutter/widgets.dart';
import 'pages/main_page.dart'; 
import 'pages/old_extened_nested_scroll_view_demo.dart'; 

RouteResult getRouteResult({String name, Map<String, dynamic> arguments}) {
  switch (name) {
    case "fluttercandies://mainpage":
      return RouteResult(widget: MainPage(),  routeName: "MainPage",  );
    case "fluttercandies://Old":
      return RouteResult(widget: OldExtendedNestedScrollViewDemo(),  routeName: "Old",  description: "extended nested scroll view to fix pinned header and inner scrollables sync issues.",);
   default:
      return RouteResult();
  }
}

class RouteResult {
  /// The Widget return base on route
  final Widget widget;

  /// Whether show this route with status bar.
  final bool showStatusBar;

  /// The route name to track page
  final String routeName;

  /// The type of page route
  final PageRouteType pageRouteType;

  /// The description of route
  final String description;

  const RouteResult(
      {this.widget,
      this.showStatusBar = true,
      this.routeName = '',
      this.pageRouteType,
      this.description = ''});
}

 enum PageRouteType { material, cupertino, transparent }

List<String> routeNames = ["fluttercandies://mainpage","fluttercandies://Old"];